spring:
  profiles:
    active:
      # Charge la variable d'environnement APP_PROFILE
      # et si elle n'existe pas, prend la valeur dev
      - ${APP_PROFILE:dev}

server:
  port: 8080

logging:
  level:
    root: INFO
    fr.kira.formation.spring.democrud: DEBUG
    fr.kira.formation.spring.democrud.personnes: TRACE