spring:
  profiles:
    active:
      # Charge la variable d'environnement APP_PROFILE
      # et si elle n'existe pas, prend la valeur dev
      - ${APP_PROFILE:dev}
server:
  port: ${API_PORT:8080}

